#!/usr/bin/env python3
"""Scaffold a Reindeer Chopper plugin from the bundled template."""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

SAFE_ID = re.compile(r"^[A-Za-z0-9_-]+$")
TEXT_SUFFIXES = {".json", ".js", ".md", ".txt", ".yaml", ".yml"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a plugin directory from assets/node-plugin-template.",
    )
    parser.add_argument("--id", required=True, help="Plugin id (letters, numbers, _, -)")
    parser.add_argument("--name", required=True, help="Plugin display name")
    parser.add_argument(
        "--description",
        default="Plugin generated by reindeer-chopper-plugin-creator",
        help="Description written into plugin.json",
    )
    parser.add_argument(
        "--dest",
        required=True,
        help="Destination root; output directory becomes <dest>/<id>",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite destination plugin folder if it already exists",
    )
    return parser.parse_args()


def ensure_safe_id(plugin_id: str) -> None:
    if not SAFE_ID.fullmatch(plugin_id):
        raise ValueError("Plugin id must contain only letters, numbers, '_' or '-'")


def replace_tokens(path: Path, tokens: dict[str, str]) -> None:
    if path.suffix not in TEXT_SUFFIXES:
        return
    text = path.read_text(encoding="utf-8")
    for key, value in tokens.items():
        text = text.replace(key, value)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    args = parse_args()
    try:
        ensure_safe_id(args.id)
    except ValueError as exc:
        print(f"[ERROR] {exc}")
        return 1

    script_dir = Path(__file__).resolve().parent
    template_dir = script_dir.parent / "assets" / "node-plugin-template"
    if not template_dir.is_dir():
        print(f"[ERROR] Template directory not found: {template_dir}")
        return 1

    dest_root = Path(args.dest).expanduser().resolve()
    dest_root.mkdir(parents=True, exist_ok=True)
    plugin_dir = dest_root / args.id

    if plugin_dir.exists():
        if not args.force:
            print(f"[ERROR] Destination already exists: {plugin_dir}")
            print("        Use --force to replace it.")
            return 1
        shutil.rmtree(plugin_dir)

    shutil.copytree(template_dir, plugin_dir)

    tokens = {
        "__PLUGIN_ID__": args.id,
        "__PLUGIN_NAME__": args.name,
        "__PLUGIN_DESCRIPTION__": args.description,
    }
    for file_path in plugin_dir.rglob("*"):
        if file_path.is_file():
            replace_tokens(file_path, tokens)

    print(f"[OK] Plugin scaffolded: {plugin_dir}")
    print("Next steps:")
    print("1. Edit index.js logic for your real task.")
    print(f"2. Validate: python3 {script_dir / 'validate_plugin.py'} {plugin_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
